apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./clusters/gke-demo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
